site_name: "Lecture Notes: CloudComputing, DevOps, and AI"
site_description: "A Practitioners Guide"
site_author: "Gregor von Laszewski"

repo_url: https://github.com/cloudmesh-ai/cloudmesh-ai-lecture/
edit_uri: edit/main/docs/

theme:
  name: material

  custom_dir: docs/stylesheets
  features:
    - content.code.copy
    - content.full_width
    - content.action.edit

# Any file matching these patterns will be treated as a draft
draft_docs: |
  drafts/*

hooks:
  - hooks/presentation_links.py

plugins:
  - meta
  - blog
  - caption
  - search
  - exclude-search:
      exclude:
        - "LOCAL/*"  
  - glightbox
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - include-markdown


  #- slides:
  #    marp_themes:
  #      - themes/bundle.css


exclude_docs: |
  drafts/
  LOCAL/
  **/*.bak.md


markdown_extensions:
  - toc:
      permalink: true #
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_style: colorful
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - pymdownx.blocks.html
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - custom.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/move_presentation_button.js


validation:
  links:
    absolute_links: relative_to_docs

    
nav:
  - Home: index.md
  - 🔵 Oct-22: lecture/oct-container.md
  - 🔵 Oct-15: lecture/oct-devops.md
  - 🔴 Oct-08: lecture/oct8.md
  - 🟢 Oct-01: lecture/oct1.md
  - TABLE OF CONTENT: lecture/luc.md
  - LECTURES:
    - 🔴 OVERVIEW:
      - 🟢 Introduction: lecture/syllabus/cloud-computing-devops-ai-syllabus.pdf
      - 🟢 Syllabus: lecture/01.1-syllabus.md
      - 🟢 Contribute: lecture/01.2-contribute-lecture-notes.md
      - 🟢 Supplemental: lecture/01.4-supplemental.md
      - 🟢 Piazza: lecture/01.5-piazza.md
      - 🟢 Videos: lecture/videos.md
      - 🟢🔴 ACCOUNTS:
        - 🟢 Local: section/accounts/local.md
        - 🟢 Access: section/accounts/access-ci.md
        - 🟢 Chameleon: section/accounts/chameleon.md
        - 🔴 AWS: section/accounts/aws.md
        - 🔴 Azure: section/accounts/azure.md
        - 🔴 Google: section/accounts/google.md
    - 🟢 CLOUD:
      - L2.1.1 🟢 Introduction: section/cloud/fundamentals/introduction.md
      - L2.1.2 🟢 Privacy: section/cloud/topics/privacy.md
      - L2.1.3 🟢 Network: section/network/network.md
    - 🟢🔴 VIRTUALIZATION:
      - 🟢🔴 Vm:
        - 🟢 Virtualization: section/cloud/fundamentals/virtualization.md
        - 🟢 VM Technologies: section/cloud/fundamentals/virtual-machine-technologies.md
        - 🟢 VM Summary: section/cloud/fundamentals/virtualization-landscape.md
        - Local:
          - 🟢 Overview: section/cloud/platforms/local/vm-status.md
          - 🟢 Multipass: section/cloud/platforms/local/multipass.md
          - 🟢 Qemu: section/cloud/platforms/local/qemu.md
          - 🟢 Vagrant: section/cloud/platforms/local/vagrant.md
          - ⚪ Virsh: section/cloud/platforms/local/virsh.md
          - ⚪ Virtualbox: section/cloud/platforms/local/virtualbox.md
          - 🟢 WSL2: section/cloud/platforms/local/wsl2.md
          - 🟢 WSL2 SSH: section/cloud/platforms/local/wsl2-ssh.md
          - ⚪ Lima: section/cloud/platforms/local/lima.md
          - ⚪ UTM: section/cloud/platforms/local/utm.md
          - Different Host Architecture:
            - 🟢 macOS: section/cloud/architecture/other-architecture-with-vmon-mac.md
            - 🟢 Windows: section/cloud/architecture/other-architecture-with-vmon-windows.md
        - Academia:
          - Jetstream:
            - 🟢 Quickstart: section/cloud/platforms/jetstream/jetstream-vm.md
            - 🟢 Hosting a Website: section/cloud/platforms/jetstream/jetstream-mkdocs.md
            - 🟢 Multiple VMs: section/cloud/platforms/jetstream/jetstream-multi.md
            - 🟢 Cost: section/cloud/platforms/jetstream/jetstream-cost.md
          - Chameleon:
            - 🟢 Horizon: section/cloud/platforms/chameleon/horizon.md
            - 🟢 os-chi: section/cloud/platforms/chameleon/python-chi.md
            - 🟢 os-command: section/cloud/platforms/chameleon/os-commandline.md
            - 🟢 Libcloud: section/cloud/topics/libcloud.md
            - 🟢 os-python: section/cloud/platforms/chameleon/os-python.md
            - 🟢 Cost: section/cloud/platforms/chameleon/cost.md
            - 🔴 VMs via Heat: section/cloud/platforms/chameleon/chameleon-multi-heat.md
          - 🔴 OpenStack:
            - 🟢 Reduce Cost: section/cloud/openstack/openstack-reduce-cost.md
          - 🔴 Openstack Heat:
            - 🔴 Introduction: section/cloud/openstack/openstack-heat.md
            - 🔵 VMs via Heat: section/cloud/platforms/chameleon/chameleon-multi-heat.md
            - 🔴 Shared Web Service: section/cloud/openstack/openstack-heat-fast-api-project-wide-access.md
            - 🔴 Bastian Web Service: section/cloud/openstack/openstack-heat-fastapi.md
          - Public Clouds:
            - 🔴 AWS Install: section/cloud/vm-cloud/aws-install-chapter.md
            - 🔴 AWS Boto: section/cloud/vm-cloud/aws-boto-chapter.md
            - 🔴 Azure Install: section/cloud/vm-cloud/azure install-chapter.md
            - 🔴 Azure SDK: section/cloud/vm-cloud/azure-sdk-chapter.md
            - 🔴 Google Install: section/cloud/vm-cloud/gcp-install-chapter.md
            - 🔴 Google SDK: section/cloud/vm-cloud/google-sdk-chapter.md
      - 🔵 Container:
        - 🔵 Docker: section/container/foundations/docker.md
        - 🔵 Kubernetes:
          - 🔵 Introduction: section/container/orchestration/kubernetes.md
          - 🔵 Local Deployment: section/container/orchestration/kubernetes-local.md
          - 🔵 Advanced:
            - 🔵 HPA Autoscaling: section/container/kubernetes-advanced/hpa-autoscaling.md
            - 🔵 RPS Autoscaling: section/container/kubernetes-advanced/rps-autoscaling.md
          - 🔵 Package Management:
            - 🔵 Helm: section/container/specialized/helm.md
        - 🔵 Orchestration:
          - 🔵 OpenShift: section/container/orchestration/openshift.md
          - 🔵 Comparison: section/container/orchestration/orchestration-comparison.md
        - 🔵 Apptainer: section/container/foundations/apptainer.md
        - 🔵 Podman: section/container/foundations/podman.md
        - 🔵 Podman vs Docker: section/container/foundations/podman-and-co.md
        - 🔵 Comparison: section/container/container-tool-comparison.md
        - 🔵 Openstack and Containers:
          - 🔵 Openstack: section/cloud/openstack/openstack.md
          - 🔵 Containers: section/container/openstack/openstack-containers.md 
          - 🔵 Chameleon: section/container/openstack/openstack-chameleon-containers.md
          - 🔵 Jetstream: section/container/openstack/openstack-jetstream-container.md    
    - 🔴 DEVOPS:
      - 🔴 Introduction: section/devops/devops.md
      - 🔴 Continuous Integration & Deployment:
          - 🔴 Fundamentals: section/devops/devop-ci.md
          - 🔴 Teams: section/devops/devops-team.md
          - 🟢 Make: section/devops/make.md
          - 🔴 GitHub Workflows: section/devops/github-workflows.md
          - 🔴 Workflow Security: section/devops/github-workflow-security.md
          - 🔴 Travis CI: section/devops/travis.md
          - 🔴 CircleCI: section/devops/circleci.md
          - 🔴 Jenkins Orchestration: section/devops/jenkins.md
      - 🔴 Infrastructure as Code:
          - 🔴 Overview: section/devops/devops-iac.md
          - 🔴 Provisioning with Terraform: section/devops/terraform.md
          - 🔴 Configuration with Ansible: section/devops/ansible.md
          - 🔴 Puppet: section/devops/puppet.md
      - 🔵 Cloud DevOps:
          - 🔵 GitOps Fundamentals: section/devops/gitops-fundamentals.md
          - 🔵 ArgoCD: section/devops/argocd.md
          - 🔵 AWS: section/devops/devop-aws.md
          - 🔵 Azure: section/devops/devop-azure-monitor.md
    - 🟡 SERVICES:
      - 🟡 REST:
        - 🟢 REST Services: section/rest/rest.md      
        - 🟡 REST AI: section/rest/rest-ai.md      
        - 🟡 REST LLM Mock: section/rest/rest-llm-mock-openai.md
      - 🔵 LLM:
        - 🔵🟡 LLM on CPUs: section/llm/hardware/llm-cpu-all.md
        - 🔵🟡 LLM on Jetstream: section/llm/hardware/llm-jetstream.md
        - 🔵⚪ LLM on Spark: section/llm/hardware/llm-spark.md
        - 🔵⚪ LLM on AmSC: section/llm/hardware/llm-amsc.md
  - ASSIGNMENTS:
    - 🟢 Overview: lecture/assignments/overview.md
    - 🟢 Weekly (LUC 388,488): lecture/assignments/assignments.md
    - 🟡 Project Ideas: lecture/assignments/ideas.md
  - 🟡 AI Fundamentals:
    - Scikit-learn:
      - ⚪ Introduction: section/ai/skit-learn/scikit-learn.md
      - 🟡 Kmeans: section/ai/skit-learn/scikit-kmeans.md
  - 🟢 CLOUDMESH:
    - 🟢 Common: section/python/cloudmesh-ai-common.md
    - 🟢 YAMLDB: section/python/python-yamldb.md
    - 🟢 Hostlist: section/python/python-hostlist.md
  - 🟡 PYTHON:
    - ⚪ Introduction: section/python/python-intro.md
    - ⚪ Installation: section/python/python-install.md
    - Getting Started:
      - ⚪ Interactive: section/python/python-interactive.md
      - ⚪ Editor: section/python/python-editor.md
      - ⚪ Language: section/python/language.md
    - 🟢  Virtual Environments:
      - ⚪ Uv: section/python/python-uv.md
      - ⚪ Hatch: section/python/python-hatch.md
      - ⚪ Hatch vs uv: section/python/python-hatch-vs-uv.md
      - 🟢 Pipx: section/python/python-pipx.md
    - 🟡 Commands:
      - 🟡 Click: section/python/python-click.md
      - ⚪ DocOpts: section/python/python-docopts.md
      - ⚪ Argparse: section/python/python-argparse.md
      - ⚪ CMD: section/python/python-cmd.md
    - 🟡 Processes:
      - 🟡 Subprocess: section/python/python-subprocess.md
      - ⚪ Parallel: section/python/python-parallel.md
      - ⚪ Queues: section/python/python-queue.md
      - ⚪ Schedulers: section/python/python-scheduler.md
    - ⚪ Data:
      - ⚪ Basic Data: section/python/python-data.md
      - ⚪ Wordcount: section/python/python-wordcount.md
    - ⚪ Graphs:
      - ⚪ Graph: section/python/python-graph.md
      - ⚪ Matplotlib: section/python/python-matplotlib.md
    - ⚪ Security:
      - ⚪ SSL/TLS: section/python/python-ssl.md
      - ⚪ SSH: section/python/python-ssh.md
    - 🟡 Development and DevOps:
      - 🟡 Type Hinting and Static Analysis: section/python/python-type-hints.md
      - 🟡 Testing: section/python/python-testing.md
      - 🟡 Logging and Monitoring: section/python/python-logging.md
      - 🟡 Packaging and Distribution: section/python/python-pyproject.md

  - 🟢⚪ LINUX:
    - ⚪ Introduction: section/linux/linux.md
    - ⚪ ZSH: section/linux/zsh.md
    - ⚪ Text one Liners: section/linux/text.md
    - ⚪ RefCards: section/linux/refcards.md
    - ⚪ Ubuntu CLI Cheat Sheet: section/linux/ubuntu-cheatsheet.md
    - 🟢 Gitbash: section/linux/gitbash.md
    - 🟢 Github: section/linux/github.md
    - 🟢 Gh CLI: section/linux/gh.md
    - 🟢 SSH: section/linux/ssh.md
    - 🟢 SSH on Windows: section/linux/ssh-windows.md
    - ⚪ Recording: section/linux/recording.md
  - 🟢⚪  WRITING:
    - ⚪ Plagarism: section/writing/plagiarism.md
    - 🟢 Markdown: section/writing/markdown.md
    - 🟢 Technical Reports: section/writing/report.md
    - ⚪ ACM Markdown: section/writing/acm-markdown.md
    - ⚪ LaTeX with Overleaf and Markdown: section/writing/overleaf.md
    - 🟢 Mkdocs: section/writing/mkdocs.md
    - ⚪ Emacs: section/writing/emacs.md
    - 🟢 Diagrams:
      - ⚪ PPT: section/writing/ppt.md
      - 🟢 Mermaid: section/writing/mermaid.md
      - 🟢 Graphviz: section/writing/graphviz.md
      - ⚪ Blockdiag: section/writing/blockdiag.md
      
  - ACKNOWLEDGEMENTS:
    - ⚪ Acknowledgments: section/acknowledgements/acknowledgements.md

#   - Google Colab: section/google-colab/python-google-colab.md