site_name: "Lecture Notes: CloudComputing, DevOps, and AI"
site_description: "A Practitioners Guide"
site_author: "Gregor von Laszewski"

repo_url: https://github.com/cloudmesh-ai/cloudmesh-ai-lecture
edit_uri: /edit/main/docs/

theme:
  name: material

  custom_dir: docs/stylesheets
  features:
    - content.code.copy
    - content.full_width
    

# Any file matching these patterns will be treated as a draft
draft_docs: |
  drafts/*

plugins:
  - meta
  - blog
  - caption
  - search
  - exclude-search:
      exclude:
        - "LOCAL/*"  
  - glightbox
  
exclude_docs: |
  drafts/
  LOCAL/

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:

      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_style: colorful
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - custom.css

extra_javascript:
  - javascripts/show_source.js
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - Home: index.md
  - LECTURES:
    - OVERVIEW:
      - L.1.0 Introduction: lecture/syllabus/cloud-computing-devops-ai-syllabus.pdf
      - L.1.1 Syllabus: lecture/01.1-syllabus.md
      - L.1.2 Contribute: lecture/01.2-contribute-lecture-notes.md
      - L.1.3 Supplemental: lecture/01.4-supplemental.md
      - L.1.4 Piazza: lecture/01.5-piazza.md
      - L.1.5 ACCOUNTS:
        - L.1.5.1 Local: lecture/accounts/local.md
        - L.1.5.2 Access: lecture/accounts/access-ci.md
        - L.1.5.3 Chameleon: lecture/accounts/chameleon.md
        - L.1.5.4 AWS: lecture/accounts/aws.md
        - L.1.5.5 Azure: lecture/accounts/azure.md
        - L.1.5.6 Google: lecture/accounts/google.md
    - CLOUD:
      - L2.1.1 Introduction: lecture/cloud/introduction.md
      - L2.1.2 Virtualization: lecture/cloud/virtualization.md
      - L2.1.3 VM Technologies: lecture/cloud/virtual-machine-technologies.md
      - L2.1.4 VM Summary: lecture/cloud/virtualization-landscape.md
      - L2.2 Local: 
        - L2.2.1 Overview: section/cloud/local/vm-status.md        
        - L2.2.1 Multipass: section/cloud/local/multipass.md
        - L2.2.1 Qemu: section/cloud/local/qemu.md
        - L2.2.1 Vagrant: section/cloud/local/vagrant.md
        - L2.2.1 Virsh: section/cloud/local/virsh.md
        - L2.2.1 Virtualbox: section/cloud/local/virtualbox.md
      - L2.3 Academia:
        - L2.3.1 Jetstream:
          - Quickstart: section/cloud/jetstream/jetstream-vm.md
          - Hosting a Website: section/cloud/jetstream/jetstream-mkdocs.md
          - Multiple VMs: section/cloud/jetstream/jetstream-multi.md
          - Cost: section/cloud/jetstream/jetstream-cost.md 
        - L2.3.2 Chameleon:
          - Horizon: section/cloud/chameleon/horizon.md
          - os-chi: section/cloud/chameleon/python-chi.md
          - os-command: section/cloud/chameleon/os-commandline.md
          - libcloud: section/cloud/chameleon/libcloud.md
          - os-python: section/cloud/chameleon/os-python.md
        
  - ASSIGNMENTS:
    - Overview: lecture/assignments/overview.md
    - LUC_388_488: lecture/assignments/assignments.md
  - '---': '#separator'

  - PYTHON:
    - P.1 Introduction: section/python/python-intro.md
    - P.2 Installation: section/python/python-install.md
    - P.3 Getting Started:
      - P.3.1 Interactive: section/python/python-interactive.md
      - P.3.2 Editor: section/python/python-editor.md
      - P.3.3 Language: section/python/language.md
    - P.5 Commands:
      - P.5.1 Click: section/python/python-click.md
      - P.5.2 DocOpts: section/python/python-docopts.md
      - P.5.3 CMD: section/python/python-cmd.md
    - P.6 Processes:
      - P.6.1 Subprocess: section/python/python-subprocess.md
      - P.6.2 Parallel: section/python/python-parallel.md
      - P.6.3 Queues: section/python/python-queue.md
      - P.6.4 Schedulers: section/python/python-scheduler.md
    - P.7 Data:
      - P.7.1 Basic Data: section/python/python-data.md
      - P.7.2 Wordcount: section/python/python-wordcount.md
    - P.8 Graphs:
      - P.8.1 Graph: section/python/python-graph.md
      - P.8.2 Matplotlib: section/python/python-matplotlib.md
    - P.9 Security:
      - P.9.1 SSL/TLS: section/python/python-ssl.md
      - P.9.2 SSH: section/python/python-ssh.md

  - LINUX:
    - L.1 Introduction: section/linux/linux.md
    - L.2 Text one Liners: section/linux/text.md
    - L.3.1 RefCards: section/linux/refcards.md
    - L.3.2 Ubuntu CLI Cheat Sheet: section/linux/ubuntu-cheatsheet.md
    - L.4 SSH: section/linux/ssh.md
    - L.5 SSH on Windows: section/linux/ssh-windows.md
    - L.6 ZSH: section/linux/zsh.md
    - L.7 Recording: section/linux/recording.md

  - WRITING:
    - W.1 Plagarism: section/writing/plagiarism.md
    - W.2 Markdown: section/writing/markdown.md
    - W.3 Emacs: section/writing/emacs.md
    - W.4 Diagrams:
      - W.4.1 PPT: section/writing/ppt.md
      - W.4.2 Mermaid: section/writing/mermaid.md
      - W.4.3 Graphviz: section/writing/graphviz.md
  - ACKNOWLEDGEMENTS:
    - A.1 Acknowledgments: section/acknowledgements/acknowledgements.md

  #- CLOUD:
  #  - VIRTUALIZATION:
  #    - Introduction: lecture/cloud/virtualization.md
  #    - VMs: lecture/cloud/virtualmachines.md
  #  - LOCAL:
  #    - Overview: section/cloud/local/vm-status.md
  #    - Multipass: section/cloud/local/multipass.md
  #    - Qemu: section/cloud/local/qemu.md
  #    - Virsh: section/cloud/local/virsh.md
  #    - Vagrant: section/cloud/local/vagrant.md
  #    - Virtualbox: section/cloud/local/virtualbox.md
  #- LLM:
  #  - Jetstream LLM: section/llm/jetstream.md 
  
  #- DEVOPS:
  #  - DevOps.1 Introduction: section/devops/devops.md
  #  - DevOps.2 Ansible: section/devops/ansible.md
  #  - DevOps.3 Puppet: section/devops/puppet.md
  #  - DevOps.4 Terraform: section/devops/terraform.md
  #  - DevOps.5 Travis: section/devops/travis.md
  #  - DevOps.6 AWS: section/devops/devop-aws.md
  #  - DevOps.7 Azure: section/devops/evop-azure-monitor.md
  #  - DevOps.8 Continuous Integration: section/devops/devop-ci.md
  #  - DevOps.9 IAC: section/devops/devops-iac.md
    # - DevOps.6 CirleCI:  section/devops/circleci.md
  #- HYPERVISOR:
  #  - H.1 Virtualization: section/cloud//virtualization.md
  #  - H.2 Qemu: section/cloud/qemu.md
  #  - H.3 Virsh: section/cloud/virsh.md
  #  - H.4 Multipass: section/cloud/multipass.md
  #  - H.5 Vagrant: section/cloud/vagrant.md

    #docs/section/cloud/arch-scheduling.md
    #docs/section/cloud/arch.md
    #docs/section/cloud/cloud-foundry.md
    #docs/section/cloud/datacenter.md
    #docs/section/cloud/definition.md
    #docs/section/cloud/gregor.md
    #docs/section/cloud/multipass.md
    #docs/section/cloud/packer.md
    #docs/section/cloud/qemu.md
    #docs/section/cloud/use-cases.md
    #docs/section/cloud/vagrant.md
    #docs/section/cloud/virsh.md
    #docs/section/cloud/virtualbox.md
    #docs/section/cloud/virtualization.md

 # - REFERENCES:
 # - CLOUDMESH:
 #      - Introduction: section/cloudmesh/introduction.md
 #      - Installation: section/cloudmesh/installation.md
 #      - Console: section/cloudmesh/console.md
 #      - Dict: section/cloudmesh/dict.md
 #      - Shell: section/cloudmesh/shell.md
 #      - Stopwatch: section/cloudmesh/stopwatch.md
 #      - Python Cmd5: section/cloudmesh/python-cmd5.md
 #      - Exercises: section/cloudmesh/exercises.md
 #  - LIBRARIES:
 #      - Libraries: section/python/python-libraries.md
 #      - Data: section/python/python-data.md
 #      - Matplotlib: section/python/python-matplotlib.md
 #      - Docopts: section/python/python-docopts.md
 #      - OpenCV: section/opencv/opencv.md
 #      - Secchi: section/opencv/secchi.md
 #  - OTHER:
 #      - Wordcount: section/python/python-wordcount.md
 #      - Numpy: section/numpy/numpy.md
 #      - Scipy: section/scipy/scipy.md
 #      - Scikit-learn: section/scikit-learn/scikit-learn.md
 #      - Random Forest: section/random-forest/random-forest.md
 #      - Parallel: section/python/python-parallel.md
 #      - Dask: section/dask/dask.md
 #  - APPLICATIONS:
 #      - Fingerprint: section/fingerprint/fingerprint.md
 #      - Facedetection: section/facedetection/facedetection.md
 # - OUTDATED:
#   - Google Colab: section/google-colab/python-google-colab.md

